# Generated by Django 4.2.28 on 2026-02-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('2048', '2048'), ('wordle', 'Wordle'), ('reaction', 'Reaction Speed')], default='2048', max_length=20)),
                ('player_name', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
