# Generated by Django 4.2.28 on 2026-02-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kkomantledailysnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='game_type',
            field=models.CharField(choices=[('2048', '2048'), ('wordle', 'Wordle'), ('reaction', 'Reaction Speed'), ('kkomantle_challenge', 'Kkomantle Challenge')], default='2048', max_length=20),
        ),
    ]
