# Generated by Django 4.2.28 on 2026-02-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_freeboardpost_freeboardcomment_discussiontopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussiontopic',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=130, unique=True),
        ),
    ]
